/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PanelAuthRouteRouteImport } from './routes/panel/auth/route'
import { Route as PanelAppRouteRouteImport } from './routes/panel/app/route'
import { Route as PanelAuthLoginRouteImport } from './routes/panel/auth/login'
import { Route as PanelAppTradesRouteImport } from './routes/panel/app/trades'
import { Route as PanelAppTokensRouteImport } from './routes/panel/app/tokens'
import { Route as PanelAppDashboardRouteImport } from './routes/panel/app/dashboard'
import { Route as PanelAppBlogsRouteImport } from './routes/panel/app/blogs'
import { Route as PanelAppArticlesRouteImport } from './routes/panel/app/articles'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelAuthRouteRoute = PanelAuthRouteRouteImport.update({
  id: '/panel/auth',
  path: '/panel/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelAppRouteRoute = PanelAppRouteRouteImport.update({
  id: '/panel/app',
  path: '/panel/app',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelAuthLoginRoute = PanelAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PanelAuthRouteRoute,
} as any)
const PanelAppTradesRoute = PanelAppTradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => PanelAppRouteRoute,
} as any)
const PanelAppTokensRoute = PanelAppTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => PanelAppRouteRoute,
} as any)
const PanelAppDashboardRoute = PanelAppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PanelAppRouteRoute,
} as any)
const PanelAppBlogsRoute = PanelAppBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => PanelAppRouteRoute,
} as any)
const PanelAppArticlesRoute = PanelAppArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => PanelAppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/panel/app': typeof PanelAppRouteRouteWithChildren
  '/panel/auth': typeof PanelAuthRouteRouteWithChildren
  '/panel/app/articles': typeof PanelAppArticlesRoute
  '/panel/app/blogs': typeof PanelAppBlogsRoute
  '/panel/app/dashboard': typeof PanelAppDashboardRoute
  '/panel/app/tokens': typeof PanelAppTokensRoute
  '/panel/app/trades': typeof PanelAppTradesRoute
  '/panel/auth/login': typeof PanelAuthLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/panel/app': typeof PanelAppRouteRouteWithChildren
  '/panel/auth': typeof PanelAuthRouteRouteWithChildren
  '/panel/app/articles': typeof PanelAppArticlesRoute
  '/panel/app/blogs': typeof PanelAppBlogsRoute
  '/panel/app/dashboard': typeof PanelAppDashboardRoute
  '/panel/app/tokens': typeof PanelAppTokensRoute
  '/panel/app/trades': typeof PanelAppTradesRoute
  '/panel/auth/login': typeof PanelAuthLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/panel/app': typeof PanelAppRouteRouteWithChildren
  '/panel/auth': typeof PanelAuthRouteRouteWithChildren
  '/panel/app/articles': typeof PanelAppArticlesRoute
  '/panel/app/blogs': typeof PanelAppBlogsRoute
  '/panel/app/dashboard': typeof PanelAppDashboardRoute
  '/panel/app/tokens': typeof PanelAppTokensRoute
  '/panel/app/trades': typeof PanelAppTradesRoute
  '/panel/auth/login': typeof PanelAuthLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/panel/app'
    | '/panel/auth'
    | '/panel/app/articles'
    | '/panel/app/blogs'
    | '/panel/app/dashboard'
    | '/panel/app/tokens'
    | '/panel/app/trades'
    | '/panel/auth/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/panel/app'
    | '/panel/auth'
    | '/panel/app/articles'
    | '/panel/app/blogs'
    | '/panel/app/dashboard'
    | '/panel/app/tokens'
    | '/panel/app/trades'
    | '/panel/auth/login'
  id:
    | '__root__'
    | '/'
    | '/panel/app'
    | '/panel/auth'
    | '/panel/app/articles'
    | '/panel/app/blogs'
    | '/panel/app/dashboard'
    | '/panel/app/tokens'
    | '/panel/app/trades'
    | '/panel/auth/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PanelAppRouteRoute: typeof PanelAppRouteRouteWithChildren
  PanelAuthRouteRoute: typeof PanelAuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/auth': {
      id: '/panel/auth'
      path: '/panel/auth'
      fullPath: '/panel/auth'
      preLoaderRoute: typeof PanelAuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/app': {
      id: '/panel/app'
      path: '/panel/app'
      fullPath: '/panel/app'
      preLoaderRoute: typeof PanelAppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/auth/login': {
      id: '/panel/auth/login'
      path: '/login'
      fullPath: '/panel/auth/login'
      preLoaderRoute: typeof PanelAuthLoginRouteImport
      parentRoute: typeof PanelAuthRouteRoute
    }
    '/panel/app/trades': {
      id: '/panel/app/trades'
      path: '/trades'
      fullPath: '/panel/app/trades'
      preLoaderRoute: typeof PanelAppTradesRouteImport
      parentRoute: typeof PanelAppRouteRoute
    }
    '/panel/app/tokens': {
      id: '/panel/app/tokens'
      path: '/tokens'
      fullPath: '/panel/app/tokens'
      preLoaderRoute: typeof PanelAppTokensRouteImport
      parentRoute: typeof PanelAppRouteRoute
    }
    '/panel/app/dashboard': {
      id: '/panel/app/dashboard'
      path: '/dashboard'
      fullPath: '/panel/app/dashboard'
      preLoaderRoute: typeof PanelAppDashboardRouteImport
      parentRoute: typeof PanelAppRouteRoute
    }
    '/panel/app/blogs': {
      id: '/panel/app/blogs'
      path: '/blogs'
      fullPath: '/panel/app/blogs'
      preLoaderRoute: typeof PanelAppBlogsRouteImport
      parentRoute: typeof PanelAppRouteRoute
    }
    '/panel/app/articles': {
      id: '/panel/app/articles'
      path: '/articles'
      fullPath: '/panel/app/articles'
      preLoaderRoute: typeof PanelAppArticlesRouteImport
      parentRoute: typeof PanelAppRouteRoute
    }
  }
}

interface PanelAppRouteRouteChildren {
  PanelAppArticlesRoute: typeof PanelAppArticlesRoute
  PanelAppBlogsRoute: typeof PanelAppBlogsRoute
  PanelAppDashboardRoute: typeof PanelAppDashboardRoute
  PanelAppTokensRoute: typeof PanelAppTokensRoute
  PanelAppTradesRoute: typeof PanelAppTradesRoute
}

const PanelAppRouteRouteChildren: PanelAppRouteRouteChildren = {
  PanelAppArticlesRoute: PanelAppArticlesRoute,
  PanelAppBlogsRoute: PanelAppBlogsRoute,
  PanelAppDashboardRoute: PanelAppDashboardRoute,
  PanelAppTokensRoute: PanelAppTokensRoute,
  PanelAppTradesRoute: PanelAppTradesRoute,
}

const PanelAppRouteRouteWithChildren = PanelAppRouteRoute._addFileChildren(
  PanelAppRouteRouteChildren,
)

interface PanelAuthRouteRouteChildren {
  PanelAuthLoginRoute: typeof PanelAuthLoginRoute
}

const PanelAuthRouteRouteChildren: PanelAuthRouteRouteChildren = {
  PanelAuthLoginRoute: PanelAuthLoginRoute,
}

const PanelAuthRouteRouteWithChildren = PanelAuthRouteRoute._addFileChildren(
  PanelAuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PanelAppRouteRoute: PanelAppRouteRouteWithChildren,
  PanelAuthRouteRoute: PanelAuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
